services:
  backend:
    build: ./backend
    container_name: tinycrm_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/tinycrm

  frontend:
    build: ./frontend
    container_name: tinycrm_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: mongo:latest
    container_name: tinycrm_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
