version: "3"

tasks:
  pull:
    desc: "Pull the latest images for TinyCRM"
    cmds:
      - docker compose pull

  clean-images:
    desc: "Remove unused Docker images"
    cmds:
      - docker image prune -af

  build:
    desc: "Build Docker images"
    cmds:
      - docker compose build

  up:
    desc: "Start TinyCRM containers"
    cmds:
      - docker compose up -d

  down:
    desc: "Stop TinyCRM containers"
    cmds:
      - docker compose down

  logs:
    desc: "View logs for backend"
    cmds:
      - docker logs tinycrm_backend

  clean:
    desc: "Remove all containers and volumes"
    cmds:
      - docker compose down -v

  rebuild:
    desc: "Fully clean, build, and restart TinyCRM"
    cmds:
      - task down
      - task clean
      - task build
      - task up
